### PR TITLE
#4 Fix linting errors

### LINKED ISSUE #4: fix linting errors
let's get the build passing so we have a nice start and a bright future

### LINKED ISSUE #8: address gitguardian security issues
this requires 
1 - removing the exposed secrets
2 - removing them from the history and any branches which they appear (slightly complicated)
3 - doing the same in the upstream repo https://github.com/arthurhjorth/nlp4all (which hopefully will be defunct at some point once github detaches the fork)

### PR DESCRIPTION
**Pull request by zeyus**
Fixes #4 , fixes #8

* Removed ipynb files
* Cleaned up some unused (not all) functions
* Moved out a couple of functions to fix circular dependencies
* Indicated with some TODOs where some obvious work could be done
* Identified that we need to break things out in a lot of places and there is a HUGE saving to be made in terms of code-reuse, I didn't do that now because it's way out of scope, but there are 100x things i had to change the same code chunks
* Addressed keys stored in repo (this still needs further work, expunging)
* Fixed all linting issues, with the exception of
* * Flask / sqlalchemy "no-member" errors, we can address it later, it just means adding in some stubs
* * Unnecessary comprehensions and suggestions to change to sets/lists etc, because no doubt this will be refactored anyway
* Added some (super basic) docstrings, but as we go along and refactor stuff we need to flesh them out

✅✅✅✅✅✅✅✅ BUILD PASSING

Suggest we type hint everything we touch from now on as well.

### CODE REVIEW

**Review by franciscoabenza — APPROVED** [review]
you added the automatic installation of the list of the requirements to the github workflows

**Review by franciscoabenza — APPROVED** [review]
There was solid work here.

**Comment by franciscoabenza** [comment]
Just a reminder that here are still some linting issues to be fix related to Flask

**Comment by zeyus** [comment]
> Just a reminder that here are still some linting issues to be fix related to Flask

Yes I'll create a task for it but we can also address it when it comes up after refactoring

**Pull request merged**
